/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.factory;

import java.sql.Connection;
import com.lbt.dao.*;
import com.lbt.jdbc.*;

public class HistoryDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return HistoryDao
	 */
	public static HistoryDao create()
	{
		return new HistoryDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return HistoryDao
	 */
	public static HistoryDao create(Connection conn)
	{
		return new HistoryDaoImpl( conn );
	}

}
