/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.lbt.dao.CouponUsageDao;
import com.lbt.dto.CouponUsage;
import com.lbt.exceptions.CouponUsageDaoException;
import com.lbt.factory.CouponUsageDaoFactory;

public class CouponUsageDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByUsers(0);
		// findByCoupons(0);
		// findWhereUsageIdEquals(0);
		// findWhereUserIdEquals(0);
		// findWhereCouponIdEquals(0);
		// findWhereDateUsedEquals(null);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			CouponUsageDao _dao = getCouponUsageDao();
			CouponUsage _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByUsers'
	 * 
	 * @param userId
	 */
	public static void findByUsers(long userId)
	{
		try {
			CouponUsageDao _dao = getCouponUsageDao();
			CouponUsage _result[] = _dao.findByUsers(userId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByCoupons'
	 * 
	 * @param couponId
	 */
	public static void findByCoupons(long couponId)
	{
		try {
			CouponUsageDao _dao = getCouponUsageDao();
			CouponUsage _result[] = _dao.findByCoupons(couponId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUsageIdEquals'
	 * 
	 * @param usageId
	 */
	public static void findWhereUsageIdEquals(long usageId)
	{
		try {
			CouponUsageDao _dao = getCouponUsageDao();
			CouponUsage _result[] = _dao.findWhereUsageIdEquals(usageId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUserIdEquals'
	 * 
	 * @param userId
	 */
	public static void findWhereUserIdEquals(long userId)
	{
		try {
			CouponUsageDao _dao = getCouponUsageDao();
			CouponUsage _result[] = _dao.findWhereUserIdEquals(userId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCouponIdEquals'
	 * 
	 * @param couponId
	 */
	public static void findWhereCouponIdEquals(long couponId)
	{
		try {
			CouponUsageDao _dao = getCouponUsageDao();
			CouponUsage _result[] = _dao.findWhereCouponIdEquals(couponId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereDateUsedEquals'
	 * 
	 * @param dateUsed
	 */
	public static void findWhereDateUsedEquals(Date dateUsed)
	{
		try {
			CouponUsageDao _dao = getCouponUsageDao();
			CouponUsage _result[] = _dao.findWhereDateUsedEquals(dateUsed);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getCouponUsageDao'
	 * 
	 * @return CouponUsageDao
	 */
	public static CouponUsageDao getCouponUsageDao()
	{
		return CouponUsageDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(CouponUsage dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getUsageId() );
		buf.append( ", " );
		buf.append( dto.getUserId() );
		buf.append( ", " );
		buf.append( dto.getCouponId() );
		buf.append( ", " );
		buf.append( dto.getDateUsed() );
		System.out.println( buf.toString() );
	}

}
