/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.lbt.dao.HistoryDao;
import com.lbt.dto.History;
import com.lbt.exceptions.HistoryDaoException;
import com.lbt.factory.HistoryDaoFactory;

public class HistoryDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findBySession(0);
		// findWhereHistoryIdEquals(0);
		// findWhereSessionIdEquals(0);
		// findWherePageControllerEquals("");
		// findWherePageActionEquals("");
		// findWherePageParamsEquals("");
		// findWherePageTitleEquals("");
		// findWherePageTypeEquals(0);
		// findWhereRefererEquals("");
		// findWhereUserIpEquals("");
		// findWhereUserAgentEquals("");
		// findWhereDateEquals(null);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			HistoryDao _dao = getHistoryDao();
			History _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findBySession'
	 * 
	 * @param sessionId
	 */
	public static void findBySession(long sessionId)
	{
		try {
			HistoryDao _dao = getHistoryDao();
			History _result[] = _dao.findBySession(sessionId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereHistoryIdEquals'
	 * 
	 * @param historyId
	 */
	public static void findWhereHistoryIdEquals(long historyId)
	{
		try {
			HistoryDao _dao = getHistoryDao();
			History _result[] = _dao.findWhereHistoryIdEquals(historyId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereSessionIdEquals'
	 * 
	 * @param sessionId
	 */
	public static void findWhereSessionIdEquals(long sessionId)
	{
		try {
			HistoryDao _dao = getHistoryDao();
			History _result[] = _dao.findWhereSessionIdEquals(sessionId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePageControllerEquals'
	 * 
	 * @param pageController
	 */
	public static void findWherePageControllerEquals(String pageController)
	{
		try {
			HistoryDao _dao = getHistoryDao();
			History _result[] = _dao.findWherePageControllerEquals(pageController);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePageActionEquals'
	 * 
	 * @param pageAction
	 */
	public static void findWherePageActionEquals(String pageAction)
	{
		try {
			HistoryDao _dao = getHistoryDao();
			History _result[] = _dao.findWherePageActionEquals(pageAction);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePageParamsEquals'
	 * 
	 * @param pageParams
	 */
	public static void findWherePageParamsEquals(String pageParams)
	{
		try {
			HistoryDao _dao = getHistoryDao();
			History _result[] = _dao.findWherePageParamsEquals(pageParams);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePageTitleEquals'
	 * 
	 * @param pageTitle
	 */
	public static void findWherePageTitleEquals(String pageTitle)
	{
		try {
			HistoryDao _dao = getHistoryDao();
			History _result[] = _dao.findWherePageTitleEquals(pageTitle);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePageTypeEquals'
	 * 
	 * @param pageType
	 */
	public static void findWherePageTypeEquals(short pageType)
	{
		try {
			HistoryDao _dao = getHistoryDao();
			History _result[] = _dao.findWherePageTypeEquals(pageType);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereRefererEquals'
	 * 
	 * @param referer
	 */
	public static void findWhereRefererEquals(String referer)
	{
		try {
			HistoryDao _dao = getHistoryDao();
			History _result[] = _dao.findWhereRefererEquals(referer);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUserIpEquals'
	 * 
	 * @param userIp
	 */
	public static void findWhereUserIpEquals(String userIp)
	{
		try {
			HistoryDao _dao = getHistoryDao();
			History _result[] = _dao.findWhereUserIpEquals(userIp);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUserAgentEquals'
	 * 
	 * @param userAgent
	 */
	public static void findWhereUserAgentEquals(String userAgent)
	{
		try {
			HistoryDao _dao = getHistoryDao();
			History _result[] = _dao.findWhereUserAgentEquals(userAgent);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereDateEquals'
	 * 
	 * @param date
	 */
	public static void findWhereDateEquals(Date date)
	{
		try {
			HistoryDao _dao = getHistoryDao();
			History _result[] = _dao.findWhereDateEquals(date);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getHistoryDao'
	 * 
	 * @return HistoryDao
	 */
	public static HistoryDao getHistoryDao()
	{
		return HistoryDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(History dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getHistoryId() );
		buf.append( ", " );
		buf.append( dto.getSessionId() );
		buf.append( ", " );
		buf.append( dto.getPageController() );
		buf.append( ", " );
		buf.append( dto.getPageAction() );
		buf.append( ", " );
		buf.append( dto.getPageParams() );
		buf.append( ", " );
		buf.append( dto.getPageTitle() );
		buf.append( ", " );
		buf.append( dto.getPageType() );
		buf.append( ", " );
		buf.append( dto.getReferer() );
		buf.append( ", " );
		buf.append( dto.getUserIp() );
		buf.append( ", " );
		buf.append( dto.getUserAgent() );
		buf.append( ", " );
		buf.append( dto.getDate() );
		System.out.println( buf.toString() );
	}

}
