/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.lbt.dao.StoryPagesDao;
import com.lbt.dto.StoryPages;
import com.lbt.exceptions.StoryPagesDaoException;
import com.lbt.factory.StoryPagesDaoFactory;

public class StoryPagesDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByStories(0);
		// findWhereStoryPageIdEquals(0);
		// findWhereStoryIdEquals(0);
		// findWhereBodyEquals("");
		// findWherePageNumEquals(0);
		// findWhereImagePathEquals("");
		// findWhereImagePathMedEquals("");
		// findWhereImagePathSmlEquals("");
		// findWhereAudioPathEquals("");
		// findWhereDateCreatedEquals(null);
		// findWhereDateModifiedEquals(null);
		// findWhereUnsavedEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			StoryPagesDao _dao = getStoryPagesDao();
			StoryPages _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByStories'
	 * 
	 * @param storyId
	 */
	public static void findByStories(long storyId)
	{
		try {
			StoryPagesDao _dao = getStoryPagesDao();
			StoryPages _result[] = _dao.findByStories(storyId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereStoryPageIdEquals'
	 * 
	 * @param storyPageId
	 */
	public static void findWhereStoryPageIdEquals(long storyPageId)
	{
		try {
			StoryPagesDao _dao = getStoryPagesDao();
			StoryPages _result[] = _dao.findWhereStoryPageIdEquals(storyPageId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereStoryIdEquals'
	 * 
	 * @param storyId
	 */
	public static void findWhereStoryIdEquals(long storyId)
	{
		try {
			StoryPagesDao _dao = getStoryPagesDao();
			StoryPages _result[] = _dao.findWhereStoryIdEquals(storyId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereBodyEquals'
	 * 
	 * @param body
	 */
	public static void findWhereBodyEquals(String body)
	{
		try {
			StoryPagesDao _dao = getStoryPagesDao();
			StoryPages _result[] = _dao.findWhereBodyEquals(body);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePageNumEquals'
	 * 
	 * @param pageNum
	 */
	public static void findWherePageNumEquals(short pageNum)
	{
		try {
			StoryPagesDao _dao = getStoryPagesDao();
			StoryPages _result[] = _dao.findWherePageNumEquals(pageNum);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereImagePathEquals'
	 * 
	 * @param imagePath
	 */
	public static void findWhereImagePathEquals(String imagePath)
	{
		try {
			StoryPagesDao _dao = getStoryPagesDao();
			StoryPages _result[] = _dao.findWhereImagePathEquals(imagePath);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereImagePathMedEquals'
	 * 
	 * @param imagePathMed
	 */
	public static void findWhereImagePathMedEquals(String imagePathMed)
	{
		try {
			StoryPagesDao _dao = getStoryPagesDao();
			StoryPages _result[] = _dao.findWhereImagePathMedEquals(imagePathMed);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereImagePathSmlEquals'
	 * 
	 * @param imagePathSml
	 */
	public static void findWhereImagePathSmlEquals(String imagePathSml)
	{
		try {
			StoryPagesDao _dao = getStoryPagesDao();
			StoryPages _result[] = _dao.findWhereImagePathSmlEquals(imagePathSml);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereAudioPathEquals'
	 * 
	 * @param audioPath
	 */
	public static void findWhereAudioPathEquals(String audioPath)
	{
		try {
			StoryPagesDao _dao = getStoryPagesDao();
			StoryPages _result[] = _dao.findWhereAudioPathEquals(audioPath);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereDateCreatedEquals'
	 * 
	 * @param dateCreated
	 */
	public static void findWhereDateCreatedEquals(Date dateCreated)
	{
		try {
			StoryPagesDao _dao = getStoryPagesDao();
			StoryPages _result[] = _dao.findWhereDateCreatedEquals(dateCreated);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereDateModifiedEquals'
	 * 
	 * @param dateModified
	 */
	public static void findWhereDateModifiedEquals(Date dateModified)
	{
		try {
			StoryPagesDao _dao = getStoryPagesDao();
			StoryPages _result[] = _dao.findWhereDateModifiedEquals(dateModified);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUnsavedEquals'
	 * 
	 * @param unsaved
	 */
	public static void findWhereUnsavedEquals(short unsaved)
	{
		try {
			StoryPagesDao _dao = getStoryPagesDao();
			StoryPages _result[] = _dao.findWhereUnsavedEquals(unsaved);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getStoryPagesDao'
	 * 
	 * @return StoryPagesDao
	 */
	public static StoryPagesDao getStoryPagesDao()
	{
		return StoryPagesDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(StoryPages dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getStoryPageId() );
		buf.append( ", " );
		buf.append( dto.getStoryId() );
		buf.append( ", " );
		buf.append( dto.getBody() );
		buf.append( ", " );
		buf.append( dto.getPageNum() );
		buf.append( ", " );
		buf.append( dto.getImagePath() );
		buf.append( ", " );
		buf.append( dto.getImagePathMed() );
		buf.append( ", " );
		buf.append( dto.getImagePathSml() );
		buf.append( ", " );
		buf.append( dto.getAudioPath() );
		buf.append( ", " );
		buf.append( dto.getDateCreated() );
		buf.append( ", " );
		buf.append( dto.getDateModified() );
		buf.append( ", " );
		buf.append( dto.getUnsaved() );
		System.out.println( buf.toString() );
	}

}
