/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.dto;

import com.lbt.dao.*;
import com.lbt.factory.*;
import com.lbt.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class GiftCards implements Serializable
{
	/** 
	 * This attribute maps to the column gift_card_id in the gift_cards table.
	 */
	protected long giftCardId;

	/** 
	 * This attribute maps to the column order_id in the gift_cards table.
	 */
	protected String orderId;

	/** 
	 * This attribute maps to the column buyer_email in the gift_cards table.
	 */
	protected String buyerEmail;

	/** 
	 * This attribute maps to the column date_created in the gift_cards table.
	 */
	protected Date dateCreated;

	/** 
	 * This attribute maps to the column redemption_code in the gift_cards table.
	 */
	protected String redemptionCode;

	/** 
	 * This attribute maps to the column paid in the gift_cards table.
	 */
	protected short paid;

	/** 
	 * This attribute maps to the column date_expires in the gift_cards table.
	 */
	protected Date dateExpires;

	/** 
	 * This attribute maps to the column date_redeemed in the gift_cards table.
	 */
	protected Date dateRedeemed;

	/** 
	 * This attribute maps to the column redeemed_by in the gift_cards table.
	 */
	protected long redeemedBy;

	/** 
	 * This attribute represents whether the primitive attribute redeemedBy is null.
	 */
	protected boolean redeemedByNull = true;

	/** 
	 * This attribute maps to the column gift_receiver in the gift_cards table.
	 */
	protected String giftReceiver;

	/** 
	 * This attribute maps to the column gift_sender in the gift_cards table.
	 */
	protected String giftSender;

	/** 
	 * This attribute maps to the column gift_message in the gift_cards table.
	 */
	protected String giftMessage;

	/**
	 * Method 'GiftCards'
	 * 
	 */
	public GiftCards()
	{
	}

	/**
	 * Method 'getGiftCardId'
	 * 
	 * @return long
	 */
	public long getGiftCardId()
	{
		return giftCardId;
	}

	/**
	 * Method 'setGiftCardId'
	 * 
	 * @param giftCardId
	 */
	public void setGiftCardId(long giftCardId)
	{
		this.giftCardId = giftCardId;
	}

	/**
	 * Method 'getOrderId'
	 * 
	 * @return String
	 */
	public String getOrderId()
	{
		return orderId;
	}

	/**
	 * Method 'setOrderId'
	 * 
	 * @param orderId
	 */
	public void setOrderId(String orderId)
	{
		this.orderId = orderId;
	}

	/**
	 * Method 'getBuyerEmail'
	 * 
	 * @return String
	 */
	public String getBuyerEmail()
	{
		return buyerEmail;
	}

	/**
	 * Method 'setBuyerEmail'
	 * 
	 * @param buyerEmail
	 */
	public void setBuyerEmail(String buyerEmail)
	{
		this.buyerEmail = buyerEmail;
	}

	/**
	 * Method 'getDateCreated'
	 * 
	 * @return Date
	 */
	public Date getDateCreated()
	{
		return dateCreated;
	}

	/**
	 * Method 'setDateCreated'
	 * 
	 * @param dateCreated
	 */
	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	/**
	 * Method 'getRedemptionCode'
	 * 
	 * @return String
	 */
	public String getRedemptionCode()
	{
		return redemptionCode;
	}

	/**
	 * Method 'setRedemptionCode'
	 * 
	 * @param redemptionCode
	 */
	public void setRedemptionCode(String redemptionCode)
	{
		this.redemptionCode = redemptionCode;
	}

	/**
	 * Method 'getPaid'
	 * 
	 * @return short
	 */
	public short getPaid()
	{
		return paid;
	}

	/**
	 * Method 'setPaid'
	 * 
	 * @param paid
	 */
	public void setPaid(short paid)
	{
		this.paid = paid;
	}

	/**
	 * Method 'getDateExpires'
	 * 
	 * @return Date
	 */
	public Date getDateExpires()
	{
		return dateExpires;
	}

	/**
	 * Method 'setDateExpires'
	 * 
	 * @param dateExpires
	 */
	public void setDateExpires(Date dateExpires)
	{
		this.dateExpires = dateExpires;
	}

	/**
	 * Method 'getDateRedeemed'
	 * 
	 * @return Date
	 */
	public Date getDateRedeemed()
	{
		return dateRedeemed;
	}

	/**
	 * Method 'setDateRedeemed'
	 * 
	 * @param dateRedeemed
	 */
	public void setDateRedeemed(Date dateRedeemed)
	{
		this.dateRedeemed = dateRedeemed;
	}

	/**
	 * Method 'getRedeemedBy'
	 * 
	 * @return long
	 */
	public long getRedeemedBy()
	{
		return redeemedBy;
	}

	/**
	 * Method 'setRedeemedBy'
	 * 
	 * @param redeemedBy
	 */
	public void setRedeemedBy(long redeemedBy)
	{
		this.redeemedBy = redeemedBy;
		this.redeemedByNull = false;
	}

	/**
	 * Method 'setRedeemedByNull'
	 * 
	 * @param value
	 */
	public void setRedeemedByNull(boolean value)
	{
		this.redeemedByNull = value;
	}

	/**
	 * Method 'isRedeemedByNull'
	 * 
	 * @return boolean
	 */
	public boolean isRedeemedByNull()
	{
		return redeemedByNull;
	}

	/**
	 * Method 'getGiftReceiver'
	 * 
	 * @return String
	 */
	public String getGiftReceiver()
	{
		return giftReceiver;
	}

	/**
	 * Method 'setGiftReceiver'
	 * 
	 * @param giftReceiver
	 */
	public void setGiftReceiver(String giftReceiver)
	{
		this.giftReceiver = giftReceiver;
	}

	/**
	 * Method 'getGiftSender'
	 * 
	 * @return String
	 */
	public String getGiftSender()
	{
		return giftSender;
	}

	/**
	 * Method 'setGiftSender'
	 * 
	 * @param giftSender
	 */
	public void setGiftSender(String giftSender)
	{
		this.giftSender = giftSender;
	}

	/**
	 * Method 'getGiftMessage'
	 * 
	 * @return String
	 */
	public String getGiftMessage()
	{
		return giftMessage;
	}

	/**
	 * Method 'setGiftMessage'
	 * 
	 * @param giftMessage
	 */
	public void setGiftMessage(String giftMessage)
	{
		this.giftMessage = giftMessage;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof GiftCards)) {
			return false;
		}
		
		final GiftCards _cast = (GiftCards) _other;
		if (giftCardId != _cast.giftCardId) {
			return false;
		}
		
		if (orderId == null ? _cast.orderId != orderId : !orderId.equals( _cast.orderId )) {
			return false;
		}
		
		if (buyerEmail == null ? _cast.buyerEmail != buyerEmail : !buyerEmail.equals( _cast.buyerEmail )) {
			return false;
		}
		
		if (dateCreated == null ? _cast.dateCreated != dateCreated : !dateCreated.equals( _cast.dateCreated )) {
			return false;
		}
		
		if (redemptionCode == null ? _cast.redemptionCode != redemptionCode : !redemptionCode.equals( _cast.redemptionCode )) {
			return false;
		}
		
		if (paid != _cast.paid) {
			return false;
		}
		
		if (dateExpires == null ? _cast.dateExpires != dateExpires : !dateExpires.equals( _cast.dateExpires )) {
			return false;
		}
		
		if (dateRedeemed == null ? _cast.dateRedeemed != dateRedeemed : !dateRedeemed.equals( _cast.dateRedeemed )) {
			return false;
		}
		
		if (redeemedBy != _cast.redeemedBy) {
			return false;
		}
		
		if (redeemedByNull != _cast.redeemedByNull) {
			return false;
		}
		
		if (giftReceiver == null ? _cast.giftReceiver != giftReceiver : !giftReceiver.equals( _cast.giftReceiver )) {
			return false;
		}
		
		if (giftSender == null ? _cast.giftSender != giftSender : !giftSender.equals( _cast.giftSender )) {
			return false;
		}
		
		if (giftMessage == null ? _cast.giftMessage != giftMessage : !giftMessage.equals( _cast.giftMessage )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (giftCardId ^ (giftCardId >>> 32));
		if (orderId != null) {
			_hashCode = 29 * _hashCode + orderId.hashCode();
		}
		
		if (buyerEmail != null) {
			_hashCode = 29 * _hashCode + buyerEmail.hashCode();
		}
		
		if (dateCreated != null) {
			_hashCode = 29 * _hashCode + dateCreated.hashCode();
		}
		
		if (redemptionCode != null) {
			_hashCode = 29 * _hashCode + redemptionCode.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) paid;
		if (dateExpires != null) {
			_hashCode = 29 * _hashCode + dateExpires.hashCode();
		}
		
		if (dateRedeemed != null) {
			_hashCode = 29 * _hashCode + dateRedeemed.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) (redeemedBy ^ (redeemedBy >>> 32));
		_hashCode = 29 * _hashCode + (redeemedByNull ? 1 : 0);
		if (giftReceiver != null) {
			_hashCode = 29 * _hashCode + giftReceiver.hashCode();
		}
		
		if (giftSender != null) {
			_hashCode = 29 * _hashCode + giftSender.hashCode();
		}
		
		if (giftMessage != null) {
			_hashCode = 29 * _hashCode + giftMessage.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return GiftCardsPk
	 */
	public GiftCardsPk createPk()
	{
		return new GiftCardsPk(giftCardId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.lbt.dto.GiftCards: " );
		ret.append( "giftCardId=" + giftCardId );
		ret.append( ", orderId=" + orderId );
		ret.append( ", buyerEmail=" + buyerEmail );
		ret.append( ", dateCreated=" + dateCreated );
		ret.append( ", redemptionCode=" + redemptionCode );
		ret.append( ", paid=" + paid );
		ret.append( ", dateExpires=" + dateExpires );
		ret.append( ", dateRedeemed=" + dateRedeemed );
		ret.append( ", redeemedBy=" + redeemedBy );
		ret.append( ", giftReceiver=" + giftReceiver );
		ret.append( ", giftSender=" + giftSender );
		ret.append( ", giftMessage=" + giftMessage );
		return ret.toString();
	}

}
