/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the session_params table.
 */
public class SessionParamsPk implements Serializable
{
	protected long sessionParamId;

	/** 
	 * This attribute represents whether the primitive attribute sessionParamId is null.
	 */
	protected boolean sessionParamIdNull;

	/** 
	 * Sets the value of sessionParamId
	 */
	public void setSessionParamId(long sessionParamId)
	{
		this.sessionParamId = sessionParamId;
	}

	/** 
	 * Gets the value of sessionParamId
	 */
	public long getSessionParamId()
	{
		return sessionParamId;
	}

	/**
	 * Method 'SessionParamsPk'
	 * 
	 */
	public SessionParamsPk()
	{
	}

	/**
	 * Method 'SessionParamsPk'
	 * 
	 * @param sessionParamId
	 */
	public SessionParamsPk(final long sessionParamId)
	{
		this.sessionParamId = sessionParamId;
	}

	/** 
	 * Sets the value of sessionParamIdNull
	 */
	public void setSessionParamIdNull(boolean sessionParamIdNull)
	{
		this.sessionParamIdNull = sessionParamIdNull;
	}

	/** 
	 * Gets the value of sessionParamIdNull
	 */
	public boolean isSessionParamIdNull()
	{
		return sessionParamIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof SessionParamsPk)) {
			return false;
		}
		
		final SessionParamsPk _cast = (SessionParamsPk) _other;
		if (sessionParamId != _cast.sessionParamId) {
			return false;
		}
		
		if (sessionParamIdNull != _cast.sessionParamIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (sessionParamId ^ (sessionParamId >>> 32));
		_hashCode = 29 * _hashCode + (sessionParamIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.lbt.dto.SessionParamsPk: " );
		ret.append( "sessionParamId=" + sessionParamId );
		return ret.toString();
	}

}
