/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.dto;

import com.lbt.dao.*;
import com.lbt.factory.*;
import com.lbt.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class SharedStories implements Serializable
{
	/** 
	 * This attribute maps to the column shared_story_id in the shared_stories table.
	 */
	protected long sharedStoryId;

	/** 
	 * This attribute maps to the column user_id in the shared_stories table.
	 */
	protected long userId;

	/** 
	 * This attribute maps to the column story_id in the shared_stories table.
	 */
	protected long storyId;

	/**
	 * Method 'SharedStories'
	 * 
	 */
	public SharedStories()
	{
	}

	/**
	 * Method 'getSharedStoryId'
	 * 
	 * @return long
	 */
	public long getSharedStoryId()
	{
		return sharedStoryId;
	}

	/**
	 * Method 'setSharedStoryId'
	 * 
	 * @param sharedStoryId
	 */
	public void setSharedStoryId(long sharedStoryId)
	{
		this.sharedStoryId = sharedStoryId;
	}

	/**
	 * Method 'getUserId'
	 * 
	 * @return long
	 */
	public long getUserId()
	{
		return userId;
	}

	/**
	 * Method 'setUserId'
	 * 
	 * @param userId
	 */
	public void setUserId(long userId)
	{
		this.userId = userId;
	}

	/**
	 * Method 'getStoryId'
	 * 
	 * @return long
	 */
	public long getStoryId()
	{
		return storyId;
	}

	/**
	 * Method 'setStoryId'
	 * 
	 * @param storyId
	 */
	public void setStoryId(long storyId)
	{
		this.storyId = storyId;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof SharedStories)) {
			return false;
		}
		
		final SharedStories _cast = (SharedStories) _other;
		if (sharedStoryId != _cast.sharedStoryId) {
			return false;
		}
		
		if (userId != _cast.userId) {
			return false;
		}
		
		if (storyId != _cast.storyId) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (sharedStoryId ^ (sharedStoryId >>> 32));
		_hashCode = 29 * _hashCode + (int) (userId ^ (userId >>> 32));
		_hashCode = 29 * _hashCode + (int) (storyId ^ (storyId >>> 32));
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return SharedStoriesPk
	 */
	public SharedStoriesPk createPk()
	{
		return new SharedStoriesPk(sharedStoryId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.lbt.dto.SharedStories: " );
		ret.append( "sharedStoryId=" + sharedStoryId );
		ret.append( ", userId=" + userId );
		ret.append( ", storyId=" + storyId );
		return ret.toString();
	}

}
