/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.jdbc;

import com.lbt.dao.*;
import com.lbt.factory.*;
import java.util.Date;
import com.lbt.dto.*;
import com.lbt.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class GreenTipsDaoImpl extends AbstractDAO implements GreenTipsDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT tip_id, tip_text, date_created FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( tip_id, tip_text, date_created ) VALUES ( ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET tip_id = ?, tip_text = ?, date_created = ? WHERE tip_id = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE tip_id = ?";

	/** 
	 * Index of column tip_id
	 */
	protected static final int COLUMN_TIP_ID = 1;

	/** 
	 * Index of column tip_text
	 */
	protected static final int COLUMN_TIP_TEXT = 2;

	/** 
	 * Index of column date_created
	 */
	protected static final int COLUMN_DATE_CREATED = 3;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 3;

	/** 
	 * Index of primary-key column tip_id
	 */
	protected static final int PK_COLUMN_TIP_ID = 1;

	/** 
	 * Inserts a new row in the green_tips table.
	 */
	public GreenTipsPk insert(GreenTips dto) throws GreenTipsDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT, Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			stmt.setLong( index++, dto.getTipId() );
			stmt.setString( index++, dto.getTipText() );
			stmt.setTimestamp(index++, dto.getDateCreated()==null ? null : new java.sql.Timestamp( dto.getDateCreated().getTime() ) );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setTipId( rs.getLong( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new GreenTipsDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the green_tips table.
	 */
	public void update(GreenTipsPk pk, GreenTips dto) throws GreenTipsDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setLong( index++, dto.getTipId() );
			stmt.setString( index++, dto.getTipText() );
			stmt.setTimestamp(index++, dto.getDateCreated()==null ? null : new java.sql.Timestamp( dto.getDateCreated().getTime() ) );
			stmt.setLong( 4, pk.getTipId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new GreenTipsDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the green_tips table.
	 */
	public void delete(GreenTipsPk pk) throws GreenTipsDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getTipId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new GreenTipsDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the green_tips table that matches the specified primary-key value.
	 */
	public GreenTips findByPrimaryKey(GreenTipsPk pk) throws GreenTipsDaoException
	{
		return findByPrimaryKey( pk.getTipId() );
	}

	/** 
	 * Returns all rows from the green_tips table that match the criteria 'tip_id = :tipId'.
	 */
	public GreenTips findByPrimaryKey(long tipId) throws GreenTipsDaoException
	{
		GreenTips ret[] = findByDynamicSelect( SQL_SELECT + " WHERE tip_id = ?", new Object[] {  new Long(tipId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the green_tips table that match the criteria ''.
	 */
	public GreenTips[] findAll() throws GreenTipsDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY tip_id", null );
	}

	/** 
	 * Returns all rows from the green_tips table that match the criteria 'tip_id = :tipId'.
	 */
	public GreenTips[] findWhereTipIdEquals(long tipId) throws GreenTipsDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE tip_id = ? ORDER BY tip_id", new Object[] {  new Long(tipId) } );
	}

	/** 
	 * Returns all rows from the green_tips table that match the criteria 'tip_text = :tipText'.
	 */
	public GreenTips[] findWhereTipTextEquals(String tipText) throws GreenTipsDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE tip_text = ? ORDER BY tip_text", new Object[] { tipText } );
	}

	/** 
	 * Returns all rows from the green_tips table that match the criteria 'date_created = :dateCreated'.
	 */
	public GreenTips[] findWhereDateCreatedEquals(Date dateCreated) throws GreenTipsDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE date_created = ? ORDER BY date_created", new Object[] { dateCreated==null ? null : new java.sql.Timestamp( dateCreated.getTime() ) } );
	}

	/**
	 * Method 'GreenTipsDaoImpl'
	 * 
	 */
	public GreenTipsDaoImpl()
	{
	}

	/**
	 * Method 'GreenTipsDaoImpl'
	 * 
	 * @param userConn
	 */
	public GreenTipsDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "green_tips";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected GreenTips fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			GreenTips dto = new GreenTips();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected GreenTips[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			GreenTips dto = new GreenTips();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		GreenTips ret[] = new GreenTips[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(GreenTips dto, ResultSet rs) throws SQLException
	{
		dto.setTipId( rs.getLong( COLUMN_TIP_ID ) );
		dto.setTipText( rs.getString( COLUMN_TIP_TEXT ) );
		dto.setDateCreated( rs.getTimestamp(COLUMN_DATE_CREATED ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(GreenTips dto)
	{
	}

	/** 
	 * Returns all rows from the green_tips table that match the specified arbitrary SQL statement
	 */
	public GreenTips[] findByDynamicSelect(String sql, Object[] sqlParams) throws GreenTipsDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new GreenTipsDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the green_tips table that match the specified arbitrary SQL statement
	 */
	public GreenTips[] findByDynamicWhere(String sql, Object[] sqlParams) throws GreenTipsDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new GreenTipsDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
