/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.jdbc;

import com.lbt.dao.*;
import com.lbt.factory.*;
import com.lbt.dto.*;
import com.lbt.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class SharedStoriesDaoImpl extends AbstractDAO implements SharedStoriesDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT shared_story_id, user_id, story_id FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( shared_story_id, user_id, story_id ) VALUES ( ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET shared_story_id = ?, user_id = ?, story_id = ? WHERE shared_story_id = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE shared_story_id = ?";

	/** 
	 * Index of column shared_story_id
	 */
	protected static final int COLUMN_SHARED_STORY_ID = 1;

	/** 
	 * Index of column user_id
	 */
	protected static final int COLUMN_USER_ID = 2;

	/** 
	 * Index of column story_id
	 */
	protected static final int COLUMN_STORY_ID = 3;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 3;

	/** 
	 * Index of primary-key column shared_story_id
	 */
	protected static final int PK_COLUMN_SHARED_STORY_ID = 1;

	/** 
	 * Inserts a new row in the shared_stories table.
	 */
	public SharedStoriesPk insert(SharedStories dto) throws SharedStoriesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT, Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			stmt.setLong( index++, dto.getSharedStoryId() );
			stmt.setLong( index++, dto.getUserId() );
			stmt.setLong( index++, dto.getStoryId() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setSharedStoryId( rs.getLong( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SharedStoriesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the shared_stories table.
	 */
	public void update(SharedStoriesPk pk, SharedStories dto) throws SharedStoriesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setLong( index++, dto.getSharedStoryId() );
			stmt.setLong( index++, dto.getUserId() );
			stmt.setLong( index++, dto.getStoryId() );
			stmt.setLong( 4, pk.getSharedStoryId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SharedStoriesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the shared_stories table.
	 */
	public void delete(SharedStoriesPk pk) throws SharedStoriesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getSharedStoryId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SharedStoriesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the shared_stories table that matches the specified primary-key value.
	 */
	public SharedStories findByPrimaryKey(SharedStoriesPk pk) throws SharedStoriesDaoException
	{
		return findByPrimaryKey( pk.getSharedStoryId() );
	}

	/** 
	 * Returns all rows from the shared_stories table that match the criteria 'shared_story_id = :sharedStoryId'.
	 */
	public SharedStories findByPrimaryKey(long sharedStoryId) throws SharedStoriesDaoException
	{
		SharedStories ret[] = findByDynamicSelect( SQL_SELECT + " WHERE shared_story_id = ?", new Object[] {  new Long(sharedStoryId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the shared_stories table that match the criteria ''.
	 */
	public SharedStories[] findAll() throws SharedStoriesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY shared_story_id", null );
	}

	/** 
	 * Returns all rows from the shared_stories table that match the criteria 'user_id = :userId'.
	 */
	public SharedStories[] findByUsers(long userId) throws SharedStoriesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE user_id = ?", new Object[] {  new Long(userId) } );
	}

	/** 
	 * Returns all rows from the shared_stories table that match the criteria 'story_id = :storyId'.
	 */
	public SharedStories[] findByStories(long storyId) throws SharedStoriesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE story_id = ?", new Object[] {  new Long(storyId) } );
	}

	/** 
	 * Returns all rows from the shared_stories table that match the criteria 'shared_story_id = :sharedStoryId'.
	 */
	public SharedStories[] findWhereSharedStoryIdEquals(long sharedStoryId) throws SharedStoriesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE shared_story_id = ? ORDER BY shared_story_id", new Object[] {  new Long(sharedStoryId) } );
	}

	/** 
	 * Returns all rows from the shared_stories table that match the criteria 'user_id = :userId'.
	 */
	public SharedStories[] findWhereUserIdEquals(long userId) throws SharedStoriesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE user_id = ? ORDER BY user_id", new Object[] {  new Long(userId) } );
	}

	/** 
	 * Returns all rows from the shared_stories table that match the criteria 'story_id = :storyId'.
	 */
	public SharedStories[] findWhereStoryIdEquals(long storyId) throws SharedStoriesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE story_id = ? ORDER BY story_id", new Object[] {  new Long(storyId) } );
	}

	/**
	 * Method 'SharedStoriesDaoImpl'
	 * 
	 */
	public SharedStoriesDaoImpl()
	{
	}

	/**
	 * Method 'SharedStoriesDaoImpl'
	 * 
	 * @param userConn
	 */
	public SharedStoriesDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "shared_stories";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected SharedStories fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			SharedStories dto = new SharedStories();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected SharedStories[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			SharedStories dto = new SharedStories();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		SharedStories ret[] = new SharedStories[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(SharedStories dto, ResultSet rs) throws SQLException
	{
		dto.setSharedStoryId( rs.getLong( COLUMN_SHARED_STORY_ID ) );
		dto.setUserId( rs.getLong( COLUMN_USER_ID ) );
		dto.setStoryId( rs.getLong( COLUMN_STORY_ID ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(SharedStories dto)
	{
	}

	/** 
	 * Returns all rows from the shared_stories table that match the specified arbitrary SQL statement
	 */
	public SharedStories[] findByDynamicSelect(String sql, Object[] sqlParams) throws SharedStoriesDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SharedStoriesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the shared_stories table that match the specified arbitrary SQL statement
	 */
	public SharedStories[] findByDynamicWhere(String sql, Object[] sqlParams) throws SharedStoriesDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SharedStoriesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
