/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.jdbc;

import com.lbt.dao.*;
import com.lbt.factory.*;
import java.util.Date;
import com.lbt.dto.*;
import com.lbt.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class StoryPagesDaoImpl extends AbstractDAO implements StoryPagesDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT story_page_id, story_id, body, page_num, image_path, image_path_med, image_path_sml, audio_path, date_created, date_modified, unsaved FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( story_page_id, story_id, body, page_num, image_path, image_path_med, image_path_sml, audio_path, date_created, date_modified, unsaved ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET story_page_id = ?, story_id = ?, body = ?, page_num = ?, image_path = ?, image_path_med = ?, image_path_sml = ?, audio_path = ?, date_created = ?, date_modified = ?, unsaved = ? WHERE story_page_id = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE story_page_id = ?";

	/** 
	 * Index of column story_page_id
	 */
	protected static final int COLUMN_STORY_PAGE_ID = 1;

	/** 
	 * Index of column story_id
	 */
	protected static final int COLUMN_STORY_ID = 2;

	/** 
	 * Index of column body
	 */
	protected static final int COLUMN_BODY = 3;

	/** 
	 * Index of column page_num
	 */
	protected static final int COLUMN_PAGE_NUM = 4;

	/** 
	 * Index of column image_path
	 */
	protected static final int COLUMN_IMAGE_PATH = 5;

	/** 
	 * Index of column image_path_med
	 */
	protected static final int COLUMN_IMAGE_PATH_MED = 6;

	/** 
	 * Index of column image_path_sml
	 */
	protected static final int COLUMN_IMAGE_PATH_SML = 7;

	/** 
	 * Index of column audio_path
	 */
	protected static final int COLUMN_AUDIO_PATH = 8;

	/** 
	 * Index of column date_created
	 */
	protected static final int COLUMN_DATE_CREATED = 9;

	/** 
	 * Index of column date_modified
	 */
	protected static final int COLUMN_DATE_MODIFIED = 10;

	/** 
	 * Index of column unsaved
	 */
	protected static final int COLUMN_UNSAVED = 11;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 11;

	/** 
	 * Index of primary-key column story_page_id
	 */
	protected static final int PK_COLUMN_STORY_PAGE_ID = 1;

	/** 
	 * Inserts a new row in the story_pages table.
	 */
	public StoryPagesPk insert(StoryPages dto) throws StoryPagesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT, Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			stmt.setLong( index++, dto.getStoryPageId() );
			stmt.setLong( index++, dto.getStoryId() );
			stmt.setString( index++, dto.getBody() );
			stmt.setShort( index++, dto.getPageNum() );
			stmt.setString( index++, dto.getImagePath() );
			stmt.setString( index++, dto.getImagePathMed() );
			stmt.setString( index++, dto.getImagePathSml() );
			stmt.setString( index++, dto.getAudioPath() );
			stmt.setTimestamp(index++, dto.getDateCreated()==null ? null : new java.sql.Timestamp( dto.getDateCreated().getTime() ) );
			stmt.setTimestamp(index++, dto.getDateModified()==null ? null : new java.sql.Timestamp( dto.getDateModified().getTime() ) );
			stmt.setShort( index++, dto.getUnsaved() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setStoryPageId( rs.getLong( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StoryPagesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the story_pages table.
	 */
	public void update(StoryPagesPk pk, StoryPages dto) throws StoryPagesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setLong( index++, dto.getStoryPageId() );
			stmt.setLong( index++, dto.getStoryId() );
			stmt.setString( index++, dto.getBody() );
			stmt.setShort( index++, dto.getPageNum() );
			stmt.setString( index++, dto.getImagePath() );
			stmt.setString( index++, dto.getImagePathMed() );
			stmt.setString( index++, dto.getImagePathSml() );
			stmt.setString( index++, dto.getAudioPath() );
			stmt.setTimestamp(index++, dto.getDateCreated()==null ? null : new java.sql.Timestamp( dto.getDateCreated().getTime() ) );
			stmt.setTimestamp(index++, dto.getDateModified()==null ? null : new java.sql.Timestamp( dto.getDateModified().getTime() ) );
			stmt.setShort( index++, dto.getUnsaved() );
			stmt.setLong( 12, pk.getStoryPageId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StoryPagesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the story_pages table.
	 */
	public void delete(StoryPagesPk pk) throws StoryPagesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getStoryPageId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StoryPagesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the story_pages table that matches the specified primary-key value.
	 */
	public StoryPages findByPrimaryKey(StoryPagesPk pk) throws StoryPagesDaoException
	{
		return findByPrimaryKey( pk.getStoryPageId() );
	}

	/** 
	 * Returns all rows from the story_pages table that match the criteria 'story_page_id = :storyPageId'.
	 */
	public StoryPages findByPrimaryKey(long storyPageId) throws StoryPagesDaoException
	{
		StoryPages ret[] = findByDynamicSelect( SQL_SELECT + " WHERE story_page_id = ?", new Object[] {  new Long(storyPageId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the story_pages table that match the criteria ''.
	 */
	public StoryPages[] findAll() throws StoryPagesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY story_page_id", null );
	}

	/** 
	 * Returns all rows from the story_pages table that match the criteria 'story_id = :storyId'.
	 */
	public StoryPages[] findByStories(long storyId) throws StoryPagesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE story_id = ?", new Object[] {  new Long(storyId) } );
	}

	/** 
	 * Returns all rows from the story_pages table that match the criteria 'story_page_id = :storyPageId'.
	 */
	public StoryPages[] findWhereStoryPageIdEquals(long storyPageId) throws StoryPagesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE story_page_id = ? ORDER BY story_page_id", new Object[] {  new Long(storyPageId) } );
	}

	/** 
	 * Returns all rows from the story_pages table that match the criteria 'story_id = :storyId'.
	 */
	public StoryPages[] findWhereStoryIdEquals(long storyId) throws StoryPagesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE story_id = ? ORDER BY story_id", new Object[] {  new Long(storyId) } );
	}

	/** 
	 * Returns all rows from the story_pages table that match the criteria 'body = :body'.
	 */
	public StoryPages[] findWhereBodyEquals(String body) throws StoryPagesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE body = ? ORDER BY body", new Object[] { body } );
	}

	/** 
	 * Returns all rows from the story_pages table that match the criteria 'page_num = :pageNum'.
	 */
	public StoryPages[] findWherePageNumEquals(short pageNum) throws StoryPagesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE page_num = ? ORDER BY page_num", new Object[] {  new Short(pageNum) } );
	}

	/** 
	 * Returns all rows from the story_pages table that match the criteria 'image_path = :imagePath'.
	 */
	public StoryPages[] findWhereImagePathEquals(String imagePath) throws StoryPagesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE image_path = ? ORDER BY image_path", new Object[] { imagePath } );
	}

	/** 
	 * Returns all rows from the story_pages table that match the criteria 'image_path_med = :imagePathMed'.
	 */
	public StoryPages[] findWhereImagePathMedEquals(String imagePathMed) throws StoryPagesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE image_path_med = ? ORDER BY image_path_med", new Object[] { imagePathMed } );
	}

	/** 
	 * Returns all rows from the story_pages table that match the criteria 'image_path_sml = :imagePathSml'.
	 */
	public StoryPages[] findWhereImagePathSmlEquals(String imagePathSml) throws StoryPagesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE image_path_sml = ? ORDER BY image_path_sml", new Object[] { imagePathSml } );
	}

	/** 
	 * Returns all rows from the story_pages table that match the criteria 'audio_path = :audioPath'.
	 */
	public StoryPages[] findWhereAudioPathEquals(String audioPath) throws StoryPagesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE audio_path = ? ORDER BY audio_path", new Object[] { audioPath } );
	}

	/** 
	 * Returns all rows from the story_pages table that match the criteria 'date_created = :dateCreated'.
	 */
	public StoryPages[] findWhereDateCreatedEquals(Date dateCreated) throws StoryPagesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE date_created = ? ORDER BY date_created", new Object[] { dateCreated==null ? null : new java.sql.Timestamp( dateCreated.getTime() ) } );
	}

	/** 
	 * Returns all rows from the story_pages table that match the criteria 'date_modified = :dateModified'.
	 */
	public StoryPages[] findWhereDateModifiedEquals(Date dateModified) throws StoryPagesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE date_modified = ? ORDER BY date_modified", new Object[] { dateModified==null ? null : new java.sql.Timestamp( dateModified.getTime() ) } );
	}

	/** 
	 * Returns all rows from the story_pages table that match the criteria 'unsaved = :unsaved'.
	 */
	public StoryPages[] findWhereUnsavedEquals(short unsaved) throws StoryPagesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE unsaved = ? ORDER BY unsaved", new Object[] {  new Short(unsaved) } );
	}

	/**
	 * Method 'StoryPagesDaoImpl'
	 * 
	 */
	public StoryPagesDaoImpl()
	{
	}

	/**
	 * Method 'StoryPagesDaoImpl'
	 * 
	 * @param userConn
	 */
	public StoryPagesDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "little_bird_tales.story_pages";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected StoryPages fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			StoryPages dto = new StoryPages();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected StoryPages[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			StoryPages dto = new StoryPages();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		StoryPages ret[] = new StoryPages[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(StoryPages dto, ResultSet rs) throws SQLException
	{
		dto.setStoryPageId( rs.getLong( COLUMN_STORY_PAGE_ID ) );
		dto.setStoryId( rs.getLong( COLUMN_STORY_ID ) );
		dto.setBody( rs.getString( COLUMN_BODY ) );
		dto.setPageNum( rs.getShort( COLUMN_PAGE_NUM ) );
		dto.setImagePath( rs.getString( COLUMN_IMAGE_PATH ) );
		dto.setImagePathMed( rs.getString( COLUMN_IMAGE_PATH_MED ) );
		dto.setImagePathSml( rs.getString( COLUMN_IMAGE_PATH_SML ) );
		dto.setAudioPath( rs.getString( COLUMN_AUDIO_PATH ) );
		dto.setDateCreated( rs.getTimestamp(COLUMN_DATE_CREATED ) );
		dto.setDateModified( rs.getTimestamp(COLUMN_DATE_MODIFIED ) );
		dto.setUnsaved( rs.getShort( COLUMN_UNSAVED ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(StoryPages dto)
	{
	}

	/** 
	 * Returns all rows from the story_pages table that match the specified arbitrary SQL statement
	 */
	public StoryPages[] findByDynamicSelect(String sql, Object[] sqlParams) throws StoryPagesDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StoryPagesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the story_pages table that match the specified arbitrary SQL statement
	 */
	public StoryPages[] findByDynamicWhere(String sql, Object[] sqlParams) throws StoryPagesDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StoryPagesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
