/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.dto;

import com.lbt.dao.*;
import com.lbt.factory.*;
import com.lbt.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Contacts implements Serializable
{
	/** 
	 * This attribute maps to the column contact_id in the contacts table.
	 */
	protected long contactId;

	/** 
	 * This attribute maps to the column user_id in the contacts table.
	 */
	protected long userId;

	/** 
	 * This attribute maps to the column name in the contacts table.
	 */
	protected String name;

	/** 
	 * This attribute maps to the column email in the contacts table.
	 */
	protected String email;

	/** 
	 * This attribute maps to the column image_path in the contacts table.
	 */
	protected String imagePath;

	/** 
	 * This attribute maps to the column date_created in the contacts table.
	 */
	protected Date dateCreated;

	/** 
	 * This attribute maps to the column date_modified in the contacts table.
	 */
	protected Date dateModified;

	/**
	 * Method 'Contacts'
	 * 
	 */
	public Contacts()
	{
	}

	/**
	 * Method 'getContactId'
	 * 
	 * @return long
	 */
	public long getContactId()
	{
		return contactId;
	}

	/**
	 * Method 'setContactId'
	 * 
	 * @param contactId
	 */
	public void setContactId(long contactId)
	{
		this.contactId = contactId;
	}

	/**
	 * Method 'getUserId'
	 * 
	 * @return long
	 */
	public long getUserId()
	{
		return userId;
	}

	/**
	 * Method 'setUserId'
	 * 
	 * @param userId
	 */
	public void setUserId(long userId)
	{
		this.userId = userId;
	}

	/**
	 * Method 'getName'
	 * 
	 * @return String
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Method 'setName'
	 * 
	 * @param name
	 */
	public void setName(String name)
	{
		this.name = name;
	}

	/**
	 * Method 'getEmail'
	 * 
	 * @return String
	 */
	public String getEmail()
	{
		return email;
	}

	/**
	 * Method 'setEmail'
	 * 
	 * @param email
	 */
	public void setEmail(String email)
	{
		this.email = email;
	}

	/**
	 * Method 'getImagePath'
	 * 
	 * @return String
	 */
	public String getImagePath()
	{
		return imagePath;
	}

	/**
	 * Method 'setImagePath'
	 * 
	 * @param imagePath
	 */
	public void setImagePath(String imagePath)
	{
		this.imagePath = imagePath;
	}

	/**
	 * Method 'getDateCreated'
	 * 
	 * @return Date
	 */
	public Date getDateCreated()
	{
		return dateCreated;
	}

	/**
	 * Method 'setDateCreated'
	 * 
	 * @param dateCreated
	 */
	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	/**
	 * Method 'getDateModified'
	 * 
	 * @return Date
	 */
	public Date getDateModified()
	{
		return dateModified;
	}

	/**
	 * Method 'setDateModified'
	 * 
	 * @param dateModified
	 */
	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Contacts)) {
			return false;
		}
		
		final Contacts _cast = (Contacts) _other;
		if (contactId != _cast.contactId) {
			return false;
		}
		
		if (userId != _cast.userId) {
			return false;
		}
		
		if (name == null ? _cast.name != name : !name.equals( _cast.name )) {
			return false;
		}
		
		if (email == null ? _cast.email != email : !email.equals( _cast.email )) {
			return false;
		}
		
		if (imagePath == null ? _cast.imagePath != imagePath : !imagePath.equals( _cast.imagePath )) {
			return false;
		}
		
		if (dateCreated == null ? _cast.dateCreated != dateCreated : !dateCreated.equals( _cast.dateCreated )) {
			return false;
		}
		
		if (dateModified == null ? _cast.dateModified != dateModified : !dateModified.equals( _cast.dateModified )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (contactId ^ (contactId >>> 32));
		_hashCode = 29 * _hashCode + (int) (userId ^ (userId >>> 32));
		if (name != null) {
			_hashCode = 29 * _hashCode + name.hashCode();
		}
		
		if (email != null) {
			_hashCode = 29 * _hashCode + email.hashCode();
		}
		
		if (imagePath != null) {
			_hashCode = 29 * _hashCode + imagePath.hashCode();
		}
		
		if (dateCreated != null) {
			_hashCode = 29 * _hashCode + dateCreated.hashCode();
		}
		
		if (dateModified != null) {
			_hashCode = 29 * _hashCode + dateModified.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ContactsPk
	 */
	public ContactsPk createPk()
	{
		return new ContactsPk(contactId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.lbt.dto.Contacts: " );
		ret.append( "contactId=" + contactId );
		ret.append( ", userId=" + userId );
		ret.append( ", name=" + name );
		ret.append( ", email=" + email );
		ret.append( ", imagePath=" + imagePath );
		ret.append( ", dateCreated=" + dateCreated );
		ret.append( ", dateModified=" + dateModified );
		return ret.toString();
	}

}
