/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the contacts table.
 */
public class ContactsPk implements Serializable
{
	protected long contactId;

	/** 
	 * This attribute represents whether the primitive attribute contactId is null.
	 */
	protected boolean contactIdNull;

	/** 
	 * Sets the value of contactId
	 */
	public void setContactId(long contactId)
	{
		this.contactId = contactId;
	}

	/** 
	 * Gets the value of contactId
	 */
	public long getContactId()
	{
		return contactId;
	}

	/**
	 * Method 'ContactsPk'
	 * 
	 */
	public ContactsPk()
	{
	}

	/**
	 * Method 'ContactsPk'
	 * 
	 * @param contactId
	 */
	public ContactsPk(final long contactId)
	{
		this.contactId = contactId;
	}

	/** 
	 * Sets the value of contactIdNull
	 */
	public void setContactIdNull(boolean contactIdNull)
	{
		this.contactIdNull = contactIdNull;
	}

	/** 
	 * Gets the value of contactIdNull
	 */
	public boolean isContactIdNull()
	{
		return contactIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ContactsPk)) {
			return false;
		}
		
		final ContactsPk _cast = (ContactsPk) _other;
		if (contactId != _cast.contactId) {
			return false;
		}
		
		if (contactIdNull != _cast.contactIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (contactId ^ (contactId >>> 32));
		_hashCode = 29 * _hashCode + (contactIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.lbt.dto.ContactsPk: " );
		ret.append( "contactId=" + contactId );
		return ret.toString();
	}

}
