/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the coupon_usage table.
 */
public class CouponUsagePk implements Serializable
{
	protected long usageId;

	/** 
	 * This attribute represents whether the primitive attribute usageId is null.
	 */
	protected boolean usageIdNull;

	/** 
	 * Sets the value of usageId
	 */
	public void setUsageId(long usageId)
	{
		this.usageId = usageId;
	}

	/** 
	 * Gets the value of usageId
	 */
	public long getUsageId()
	{
		return usageId;
	}

	/**
	 * Method 'CouponUsagePk'
	 * 
	 */
	public CouponUsagePk()
	{
	}

	/**
	 * Method 'CouponUsagePk'
	 * 
	 * @param usageId
	 */
	public CouponUsagePk(final long usageId)
	{
		this.usageId = usageId;
	}

	/** 
	 * Sets the value of usageIdNull
	 */
	public void setUsageIdNull(boolean usageIdNull)
	{
		this.usageIdNull = usageIdNull;
	}

	/** 
	 * Gets the value of usageIdNull
	 */
	public boolean isUsageIdNull()
	{
		return usageIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CouponUsagePk)) {
			return false;
		}
		
		final CouponUsagePk _cast = (CouponUsagePk) _other;
		if (usageId != _cast.usageId) {
			return false;
		}
		
		if (usageIdNull != _cast.usageIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (usageId ^ (usageId >>> 32));
		_hashCode = 29 * _hashCode + (usageIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.lbt.dto.CouponUsagePk: " );
		ret.append( "usageId=" + usageId );
		return ret.toString();
	}

}
