/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.dto;

import com.lbt.dao.*;
import com.lbt.factory.*;
import com.lbt.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class CouponUsage implements Serializable
{
	/** 
	 * This attribute maps to the column usage_id in the coupon_usage table.
	 */
	protected long usageId;

	/** 
	 * This attribute maps to the column user_id in the coupon_usage table.
	 */
	protected long userId;

	/** 
	 * This attribute maps to the column coupon_id in the coupon_usage table.
	 */
	protected long couponId;

	/** 
	 * This attribute maps to the column date_used in the coupon_usage table.
	 */
	protected Date dateUsed;

	/**
	 * Method 'CouponUsage'
	 * 
	 */
	public CouponUsage()
	{
	}

	/**
	 * Method 'getUsageId'
	 * 
	 * @return long
	 */
	public long getUsageId()
	{
		return usageId;
	}

	/**
	 * Method 'setUsageId'
	 * 
	 * @param usageId
	 */
	public void setUsageId(long usageId)
	{
		this.usageId = usageId;
	}

	/**
	 * Method 'getUserId'
	 * 
	 * @return long
	 */
	public long getUserId()
	{
		return userId;
	}

	/**
	 * Method 'setUserId'
	 * 
	 * @param userId
	 */
	public void setUserId(long userId)
	{
		this.userId = userId;
	}

	/**
	 * Method 'getCouponId'
	 * 
	 * @return long
	 */
	public long getCouponId()
	{
		return couponId;
	}

	/**
	 * Method 'setCouponId'
	 * 
	 * @param couponId
	 */
	public void setCouponId(long couponId)
	{
		this.couponId = couponId;
	}

	/**
	 * Method 'getDateUsed'
	 * 
	 * @return Date
	 */
	public Date getDateUsed()
	{
		return dateUsed;
	}

	/**
	 * Method 'setDateUsed'
	 * 
	 * @param dateUsed
	 */
	public void setDateUsed(Date dateUsed)
	{
		this.dateUsed = dateUsed;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CouponUsage)) {
			return false;
		}
		
		final CouponUsage _cast = (CouponUsage) _other;
		if (usageId != _cast.usageId) {
			return false;
		}
		
		if (userId != _cast.userId) {
			return false;
		}
		
		if (couponId != _cast.couponId) {
			return false;
		}
		
		if (dateUsed == null ? _cast.dateUsed != dateUsed : !dateUsed.equals( _cast.dateUsed )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (usageId ^ (usageId >>> 32));
		_hashCode = 29 * _hashCode + (int) (userId ^ (userId >>> 32));
		_hashCode = 29 * _hashCode + (int) (couponId ^ (couponId >>> 32));
		if (dateUsed != null) {
			_hashCode = 29 * _hashCode + dateUsed.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CouponUsagePk
	 */
	public CouponUsagePk createPk()
	{
		return new CouponUsagePk(usageId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.lbt.dto.CouponUsage: " );
		ret.append( "usageId=" + usageId );
		ret.append( ", userId=" + userId );
		ret.append( ", couponId=" + couponId );
		ret.append( ", dateUsed=" + dateUsed );
		return ret.toString();
	}

}
