/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the coupons table.
 */
public class CouponsPk implements Serializable
{
	protected long couponId;

	/** 
	 * This attribute represents whether the primitive attribute couponId is null.
	 */
	protected boolean couponIdNull;

	/** 
	 * Sets the value of couponId
	 */
	public void setCouponId(long couponId)
	{
		this.couponId = couponId;
	}

	/** 
	 * Gets the value of couponId
	 */
	public long getCouponId()
	{
		return couponId;
	}

	/**
	 * Method 'CouponsPk'
	 * 
	 */
	public CouponsPk()
	{
	}

	/**
	 * Method 'CouponsPk'
	 * 
	 * @param couponId
	 */
	public CouponsPk(final long couponId)
	{
		this.couponId = couponId;
	}

	/** 
	 * Sets the value of couponIdNull
	 */
	public void setCouponIdNull(boolean couponIdNull)
	{
		this.couponIdNull = couponIdNull;
	}

	/** 
	 * Gets the value of couponIdNull
	 */
	public boolean isCouponIdNull()
	{
		return couponIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CouponsPk)) {
			return false;
		}
		
		final CouponsPk _cast = (CouponsPk) _other;
		if (couponId != _cast.couponId) {
			return false;
		}
		
		if (couponIdNull != _cast.couponIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (couponId ^ (couponId >>> 32));
		_hashCode = 29 * _hashCode + (couponIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.lbt.dto.CouponsPk: " );
		ret.append( "couponId=" + couponId );
		return ret.toString();
	}

}
