/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the gift_cards table.
 */
public class GiftCardsPk implements Serializable
{
	protected long giftCardId;

	/** 
	 * This attribute represents whether the primitive attribute giftCardId is null.
	 */
	protected boolean giftCardIdNull;

	/** 
	 * Sets the value of giftCardId
	 */
	public void setGiftCardId(long giftCardId)
	{
		this.giftCardId = giftCardId;
	}

	/** 
	 * Gets the value of giftCardId
	 */
	public long getGiftCardId()
	{
		return giftCardId;
	}

	/**
	 * Method 'GiftCardsPk'
	 * 
	 */
	public GiftCardsPk()
	{
	}

	/**
	 * Method 'GiftCardsPk'
	 * 
	 * @param giftCardId
	 */
	public GiftCardsPk(final long giftCardId)
	{
		this.giftCardId = giftCardId;
	}

	/** 
	 * Sets the value of giftCardIdNull
	 */
	public void setGiftCardIdNull(boolean giftCardIdNull)
	{
		this.giftCardIdNull = giftCardIdNull;
	}

	/** 
	 * Gets the value of giftCardIdNull
	 */
	public boolean isGiftCardIdNull()
	{
		return giftCardIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof GiftCardsPk)) {
			return false;
		}
		
		final GiftCardsPk _cast = (GiftCardsPk) _other;
		if (giftCardId != _cast.giftCardId) {
			return false;
		}
		
		if (giftCardIdNull != _cast.giftCardIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (giftCardId ^ (giftCardId >>> 32));
		_hashCode = 29 * _hashCode + (giftCardIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.lbt.dto.GiftCardsPk: " );
		ret.append( "giftCardId=" + giftCardId );
		return ret.toString();
	}

}
