/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.dto;

import com.lbt.dao.*;
import com.lbt.factory.*;
import com.lbt.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class GreenTips implements Serializable
{
	/** 
	 * This attribute maps to the column tip_id in the green_tips table.
	 */
	protected long tipId;

	/** 
	 * This attribute maps to the column tip_text in the green_tips table.
	 */
	protected String tipText;

	/** 
	 * This attribute maps to the column date_created in the green_tips table.
	 */
	protected Date dateCreated;

	/**
	 * Method 'GreenTips'
	 * 
	 */
	public GreenTips()
	{
	}

	/**
	 * Method 'getTipId'
	 * 
	 * @return long
	 */
	public long getTipId()
	{
		return tipId;
	}

	/**
	 * Method 'setTipId'
	 * 
	 * @param tipId
	 */
	public void setTipId(long tipId)
	{
		this.tipId = tipId;
	}

	/**
	 * Method 'getTipText'
	 * 
	 * @return String
	 */
	public String getTipText()
	{
		return tipText;
	}

	/**
	 * Method 'setTipText'
	 * 
	 * @param tipText
	 */
	public void setTipText(String tipText)
	{
		this.tipText = tipText;
	}

	/**
	 * Method 'getDateCreated'
	 * 
	 * @return Date
	 */
	public Date getDateCreated()
	{
		return dateCreated;
	}

	/**
	 * Method 'setDateCreated'
	 * 
	 * @param dateCreated
	 */
	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof GreenTips)) {
			return false;
		}
		
		final GreenTips _cast = (GreenTips) _other;
		if (tipId != _cast.tipId) {
			return false;
		}
		
		if (tipText == null ? _cast.tipText != tipText : !tipText.equals( _cast.tipText )) {
			return false;
		}
		
		if (dateCreated == null ? _cast.dateCreated != dateCreated : !dateCreated.equals( _cast.dateCreated )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (tipId ^ (tipId >>> 32));
		if (tipText != null) {
			_hashCode = 29 * _hashCode + tipText.hashCode();
		}
		
		if (dateCreated != null) {
			_hashCode = 29 * _hashCode + dateCreated.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return GreenTipsPk
	 */
	public GreenTipsPk createPk()
	{
		return new GreenTipsPk(tipId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.lbt.dto.GreenTips: " );
		ret.append( "tipId=" + tipId );
		ret.append( ", tipText=" + tipText );
		ret.append( ", dateCreated=" + dateCreated );
		return ret.toString();
	}

}
