/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the history table.
 */
public class HistoryPk implements Serializable
{
	protected long historyId;

	/** 
	 * This attribute represents whether the primitive attribute historyId is null.
	 */
	protected boolean historyIdNull;

	/** 
	 * Sets the value of historyId
	 */
	public void setHistoryId(long historyId)
	{
		this.historyId = historyId;
	}

	/** 
	 * Gets the value of historyId
	 */
	public long getHistoryId()
	{
		return historyId;
	}

	/**
	 * Method 'HistoryPk'
	 * 
	 */
	public HistoryPk()
	{
	}

	/**
	 * Method 'HistoryPk'
	 * 
	 * @param historyId
	 */
	public HistoryPk(final long historyId)
	{
		this.historyId = historyId;
	}

	/** 
	 * Sets the value of historyIdNull
	 */
	public void setHistoryIdNull(boolean historyIdNull)
	{
		this.historyIdNull = historyIdNull;
	}

	/** 
	 * Gets the value of historyIdNull
	 */
	public boolean isHistoryIdNull()
	{
		return historyIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof HistoryPk)) {
			return false;
		}
		
		final HistoryPk _cast = (HistoryPk) _other;
		if (historyId != _cast.historyId) {
			return false;
		}
		
		if (historyIdNull != _cast.historyIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (historyId ^ (historyId >>> 32));
		_hashCode = 29 * _hashCode + (historyIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.lbt.dto.HistoryPk: " );
		ret.append( "historyId=" + historyId );
		return ret.toString();
	}

}
