/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the stories table.
 */
public class MP4FilesPk implements Serializable
{
	protected long mp4Id;

	/** 
	 * This attribute represents whether the primitive attribute mp4Id is null.
	 */
	protected boolean mp4IdNull;

	/** 
	 * Sets the value of mp4Id
	 */
	public void setMp4Id(long mp4Id)
	{
		this.mp4Id = mp4Id;
	}

	/** 
	 * Gets the value of mp4Id
	 */
	public long getMp4Id()
	{
		return mp4Id;
	}

	/**
	 * Method 'MP4FilesPk'
	 * 
	 */
	public MP4FilesPk()
	{
	}

	/**
	 * Method 'MP4FilesPk'
	 * 
	 * @param mp4Id
	 */
	public MP4FilesPk(final long mp4Id)
	{
		this.mp4Id = mp4Id;
	}

	/** 
	 * Sets the value of mp4IdNull
	 */
	public void setMp4IdNull(boolean mp4IdNull)
	{
		this.mp4IdNull = mp4IdNull;
	}

	/** 
	 * Gets the value of mp4IdNull
	 */
	public boolean isMp4IdNull()
	{
		return mp4IdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof MP4FilesPk)) {
			return false;
		}
		
		final MP4FilesPk _cast = (MP4FilesPk) _other;
		if (mp4Id != _cast.mp4Id) {
			return false;
		}
		
		if (mp4IdNull != _cast.mp4IdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (mp4Id ^ (mp4Id >>> 32));
		_hashCode = 29 * _hashCode + (mp4IdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.lbt.dto.MP4FilesPk: " );
		ret.append( "mp4Id=" + mp4Id );
		return ret.toString();
	}

}
