/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the session table.
 */
public class SessionPk implements Serializable
{
	protected long sessionId;

	/** 
	 * This attribute represents whether the primitive attribute sessionId is null.
	 */
	protected boolean sessionIdNull;

	/** 
	 * Sets the value of sessionId
	 */
	public void setSessionId(long sessionId)
	{
		this.sessionId = sessionId;
	}

	/** 
	 * Gets the value of sessionId
	 */
	public long getSessionId()
	{
		return sessionId;
	}

	/**
	 * Method 'SessionPk'
	 * 
	 */
	public SessionPk()
	{
	}

	/**
	 * Method 'SessionPk'
	 * 
	 * @param sessionId
	 */
	public SessionPk(final long sessionId)
	{
		this.sessionId = sessionId;
	}

	/** 
	 * Sets the value of sessionIdNull
	 */
	public void setSessionIdNull(boolean sessionIdNull)
	{
		this.sessionIdNull = sessionIdNull;
	}

	/** 
	 * Gets the value of sessionIdNull
	 */
	public boolean isSessionIdNull()
	{
		return sessionIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof SessionPk)) {
			return false;
		}
		
		final SessionPk _cast = (SessionPk) _other;
		if (sessionId != _cast.sessionId) {
			return false;
		}
		
		if (sessionIdNull != _cast.sessionIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (sessionId ^ (sessionId >>> 32));
		_hashCode = 29 * _hashCode + (sessionIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.lbt.dto.SessionPk: " );
		ret.append( "sessionId=" + sessionId );
		return ret.toString();
	}

}
