/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the story_pages table.
 */
public class StoryPagesPk implements Serializable
{
	protected long storyPageId;

	/** 
	 * This attribute represents whether the primitive attribute storyPageId is null.
	 */
	protected boolean storyPageIdNull;

	/** 
	 * Sets the value of storyPageId
	 */
	public void setStoryPageId(long storyPageId)
	{
		this.storyPageId = storyPageId;
	}

	/** 
	 * Gets the value of storyPageId
	 */
	public long getStoryPageId()
	{
		return storyPageId;
	}

	/**
	 * Method 'StoryPagesPk'
	 * 
	 */
	public StoryPagesPk()
	{
	}

	/**
	 * Method 'StoryPagesPk'
	 * 
	 * @param storyPageId
	 */
	public StoryPagesPk(final long storyPageId)
	{
		this.storyPageId = storyPageId;
	}

	/** 
	 * Sets the value of storyPageIdNull
	 */
	public void setStoryPageIdNull(boolean storyPageIdNull)
	{
		this.storyPageIdNull = storyPageIdNull;
	}

	/** 
	 * Gets the value of storyPageIdNull
	 */
	public boolean isStoryPageIdNull()
	{
		return storyPageIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof StoryPagesPk)) {
			return false;
		}
		
		final StoryPagesPk _cast = (StoryPagesPk) _other;
		if (storyPageId != _cast.storyPageId) {
			return false;
		}
		
		if (storyPageIdNull != _cast.storyPageIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (storyPageId ^ (storyPageId >>> 32));
		_hashCode = 29 * _hashCode + (storyPageIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.lbt.dto.StoryPagesPk: " );
		ret.append( "storyPageId=" + storyPageId );
		return ret.toString();
	}

}
