/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.dto;

import com.lbt.dao.*;
import com.lbt.factory.*;
import com.lbt.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class StoryPages implements Serializable
{
	/** 
	 * This attribute maps to the column story_page_id in the story_pages table.
	 */
	protected long storyPageId;

	/** 
	 * This attribute maps to the column story_id in the story_pages table.
	 */
	protected long storyId;

	/** 
	 * This attribute maps to the column body in the story_pages table.
	 */
	protected String body;

	/** 
	 * This attribute maps to the column page_num in the story_pages table.
	 */
	protected short pageNum;

	/** 
	 * This attribute maps to the column image_path in the story_pages table.
	 */
	protected String imagePath;

	/** 
	 * This attribute maps to the column image_path_med in the story_pages table.
	 */
	protected String imagePathMed;

	/** 
	 * This attribute maps to the column image_path_sml in the story_pages table.
	 */
	protected String imagePathSml;

	/** 
	 * This attribute maps to the column audio_path in the story_pages table.
	 */
	protected String audioPath;

	/** 
	 * This attribute maps to the column date_created in the story_pages table.
	 */
	protected Date dateCreated;

	/** 
	 * This attribute maps to the column date_modified in the story_pages table.
	 */
	protected Date dateModified;

	/** 
	 * This attribute maps to the column unsaved in the story_pages table.
	 */
	protected short unsaved;

	/**
	 * Method 'StoryPages'
	 * 
	 */
	public StoryPages()
	{
	}

	/**
	 * Method 'getStoryPageId'
	 * 
	 * @return long
	 */
	public long getStoryPageId()
	{
		return storyPageId;
	}

	/**
	 * Method 'setStoryPageId'
	 * 
	 * @param storyPageId
	 */
	public void setStoryPageId(long storyPageId)
	{
		this.storyPageId = storyPageId;
	}

	/**
	 * Method 'getStoryId'
	 * 
	 * @return long
	 */
	public long getStoryId()
	{
		return storyId;
	}

	/**
	 * Method 'setStoryId'
	 * 
	 * @param storyId
	 */
	public void setStoryId(long storyId)
	{
		this.storyId = storyId;
	}

	/**
	 * Method 'getBody'
	 * 
	 * @return String
	 */
	public String getBody()
	{
		return body;
	}

	/**
	 * Method 'setBody'
	 * 
	 * @param body
	 */
	public void setBody(String body)
	{
		this.body = body;
	}

	/**
	 * Method 'getPageNum'
	 * 
	 * @return short
	 */
	public short getPageNum()
	{
		return pageNum;
	}

	/**
	 * Method 'setPageNum'
	 * 
	 * @param pageNum
	 */
	public void setPageNum(short pageNum)
	{
		this.pageNum = pageNum;
	}

	/**
	 * Method 'getImagePath'
	 * 
	 * @return String
	 */
	public String getImagePath()
	{
		return imagePath;
	}

	/**
	 * Method 'setImagePath'
	 * 
	 * @param imagePath
	 */
	public void setImagePath(String imagePath)
	{
		this.imagePath = imagePath;
	}

	/**
	 * Method 'getImagePathMed'
	 * 
	 * @return String
	 */
	public String getImagePathMed()
	{
		return imagePathMed;
	}

	/**
	 * Method 'setImagePathMed'
	 * 
	 * @param imagePathMed
	 */
	public void setImagePathMed(String imagePathMed)
	{
		this.imagePathMed = imagePathMed;
	}

	/**
	 * Method 'getImagePathSml'
	 * 
	 * @return String
	 */
	public String getImagePathSml()
	{
		return imagePathSml;
	}

	/**
	 * Method 'setImagePathSml'
	 * 
	 * @param imagePathSml
	 */
	public void setImagePathSml(String imagePathSml)
	{
		this.imagePathSml = imagePathSml;
	}

	/**
	 * Method 'getAudioPath'
	 * 
	 * @return String
	 */
	public String getAudioPath()
	{
		return audioPath;
	}

	/**
	 * Method 'setAudioPath'
	 * 
	 * @param audioPath
	 */
	public void setAudioPath(String audioPath)
	{
		this.audioPath = audioPath;
	}

	/**
	 * Method 'getDateCreated'
	 * 
	 * @return Date
	 */
	public Date getDateCreated()
	{
		return dateCreated;
	}

	/**
	 * Method 'setDateCreated'
	 * 
	 * @param dateCreated
	 */
	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	/**
	 * Method 'getDateModified'
	 * 
	 * @return Date
	 */
	public Date getDateModified()
	{
		return dateModified;
	}

	/**
	 * Method 'setDateModified'
	 * 
	 * @param dateModified
	 */
	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	/**
	 * Method 'getUnsaved'
	 * 
	 * @return short
	 */
	public short getUnsaved()
	{
		return unsaved;
	}

	/**
	 * Method 'setUnsaved'
	 * 
	 * @param unsaved
	 */
	public void setUnsaved(short unsaved)
	{
		this.unsaved = unsaved;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof StoryPages)) {
			return false;
		}
		
		final StoryPages _cast = (StoryPages) _other;
		if (storyPageId != _cast.storyPageId) {
			return false;
		}
		
		if (storyId != _cast.storyId) {
			return false;
		}
		
		if (body == null ? _cast.body != body : !body.equals( _cast.body )) {
			return false;
		}
		
		if (pageNum != _cast.pageNum) {
			return false;
		}
		
		if (imagePath == null ? _cast.imagePath != imagePath : !imagePath.equals( _cast.imagePath )) {
			return false;
		}
		
		if (imagePathMed == null ? _cast.imagePathMed != imagePathMed : !imagePathMed.equals( _cast.imagePathMed )) {
			return false;
		}
		
		if (imagePathSml == null ? _cast.imagePathSml != imagePathSml : !imagePathSml.equals( _cast.imagePathSml )) {
			return false;
		}
		
		if (audioPath == null ? _cast.audioPath != audioPath : !audioPath.equals( _cast.audioPath )) {
			return false;
		}
		
		if (dateCreated == null ? _cast.dateCreated != dateCreated : !dateCreated.equals( _cast.dateCreated )) {
			return false;
		}
		
		if (dateModified == null ? _cast.dateModified != dateModified : !dateModified.equals( _cast.dateModified )) {
			return false;
		}
		
		if (unsaved != _cast.unsaved) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (storyPageId ^ (storyPageId >>> 32));
		_hashCode = 29 * _hashCode + (int) (storyId ^ (storyId >>> 32));
		if (body != null) {
			_hashCode = 29 * _hashCode + body.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) pageNum;
		if (imagePath != null) {
			_hashCode = 29 * _hashCode + imagePath.hashCode();
		}
		
		if (imagePathMed != null) {
			_hashCode = 29 * _hashCode + imagePathMed.hashCode();
		}
		
		if (imagePathSml != null) {
			_hashCode = 29 * _hashCode + imagePathSml.hashCode();
		}
		
		if (audioPath != null) {
			_hashCode = 29 * _hashCode + audioPath.hashCode();
		}
		
		if (dateCreated != null) {
			_hashCode = 29 * _hashCode + dateCreated.hashCode();
		}
		
		if (dateModified != null) {
			_hashCode = 29 * _hashCode + dateModified.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) unsaved;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return StoryPagesPk
	 */
	public StoryPagesPk createPk()
	{
		return new StoryPagesPk(storyPageId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.lbt.dto.StoryPages: " );
		ret.append( "storyPageId=" + storyPageId );
		ret.append( ", storyId=" + storyId );
		ret.append( ", body=" + body );
		ret.append( ", pageNum=" + pageNum );
		ret.append( ", imagePath=" + imagePath );
		ret.append( ", imagePathMed=" + imagePathMed );
		ret.append( ", imagePathSml=" + imagePathSml );
		ret.append( ", audioPath=" + audioPath );
		ret.append( ", dateCreated=" + dateCreated );
		ret.append( ", dateModified=" + dateModified );
		ret.append( ", unsaved=" + unsaved );
		return ret.toString();
	}

}
