/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.exceptions;

public class MP4FilesDaoException extends DaoException
{
	/**
	 * Method 'MP4FilesDaoException'
	 * 
	 * @param message
	 */
	public MP4FilesDaoException(String message)
	{
		super(message);
	}

	/**
	 * Method 'MP4FilesDaoException'
	 * 
	 * @param message
	 * @param cause
	 */
	public MP4FilesDaoException(String message, Throwable cause)
	{
		super(message, cause);
	}

}
