/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.exceptions;

public class ContactsDaoException extends DaoException
{
	/**
	 * Method 'ContactsDaoException'
	 * 
	 * @param message
	 */
	public ContactsDaoException(String message)
	{
		super(message);
	}

	/**
	 * Method 'ContactsDaoException'
	 * 
	 * @param message
	 * @param cause
	 */
	public ContactsDaoException(String message, Throwable cause)
	{
		super(message, cause);
	}

}
