/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.lbt.factory;

import java.sql.Connection;
import com.lbt.dao.*;
import com.lbt.jdbc.*;

public class MP4FilesDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return MP4FilesDao
	 */
	public static MP4FilesDao create()
	{
		return new MP4FilesDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return MP4FilesDao
	 */
	public static MP4FilesDao create(Connection conn)
	{
		return new MP4FilesDaoImpl( conn );
	}

}
